name = "pso"
version = "0.1.0"
license = "license"
author = "konrad.kraemer"
maintainer = "konrad.kraemer@kit.edu"
copyright = "Copyright 2022, konrad.kraemer"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[dependencies]
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
